server:
  port: 8082

spring:
  application:
    name: ServerClient

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

